<a href="https://colab.research.google.com/github/B-h-a-v-y-a-T/MachineLearning/blob/main/Nutri_Hackathon_42_67.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Train_Data.csv')
df

,SEQN,RIAGENDR,PAQ605,BMXBMI,LBXGLU,DIQ010,LBXGLT,LBXIN,age_group
0,73564.0,2.0,2.0,35.7,110.0,2.0,150.0,14.91,Adult
1,73568.0,2.0,2.0,20.3,89.0,2.0,80.0,3.85,Adult
2,73576.0,1.0,2.0,23.2,89.0,2.0,68.0,6.14,Adult
3,73577.0,1.0,2.0,28.9,104.0,NaN,84.0,16.15,Adult
4,73580.0,2.0,1.0,35.9,103.0,2.0,81.0,10.92,Adult
...,...,...,...,...,...,...,...,...,...
1961,83711.0,2.0,2.0,33.5,100.0,2.0,73.0,6.53,Adult
1962,83712.0,1.0,2.0,30.0,93.0,2.0,208.0,13.02,Adult
1963,83713.0,1.0,2.0,23.7,103.0,2.0,124.0,21.41,Adult
1964,83718.0,2.0,2.0,27.4,90.0,2.0,108.0,4.99,Adult
1965,83727.0,1.0,2.0,24.5,NaN,2.0,108.0,3.76,Adult

In [ ]:
df.fillna(df.median(numeric_only=True), inplace=True)
df.isnull().sum()

SEQN          0
RIAGENDR      0
PAQ605        0
BMXBMI        0
LBXGLU        0
DIQ010        0
LBXGLT        0
LBXIN         0
age_group    14
dtype: int64

In [ ]:
test_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Test_Data.csv')
test_data

        SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN
0    77017.0       1.0     1.0    32.2    96.0     2.0   135.0  15.11
1    75580.0       2.0     2.0    26.3   100.0     2.0   141.0  15.26
2    73820.0       1.0     2.0    28.6   107.0     2.0   136.0   8.82
3    80489.0       2.0     1.0    22.1    93.0     2.0   111.0  12.13
4    82047.0       1.0     1.0    24.7    91.0     2.0   105.0   3.12
..       ...       ...     ...     ...     ...     ...     ...    ...
307  74150.0       2.0     2.0    21.9    82.0     2.0    82.0   2.54
308  82550.0       2.0     1.0    33.3    95.0     2.0    77.0   6.36
309  77835.0       2.0     2.0    41.5    91.0     2.0   149.0  15.52
310  79281.0       2.0     2.0    22.5    82.0     2.0    93.0   1.39
311  77214.0       1.0     2.0    16.1    96.0     2.0   197.0   8.57

[312 rows x 8 columns]

In [ ]:
df['target']= df.age_group.apply(lambda x: 1 if x == 'Senior' else 0)
df

,SEQN,RIAGENDR,PAQ605,BMXBMI,LBXGLU,DIQ010,LBXGLT,LBXIN,age_group,target
0,73564.0,2.0,2.0,35.7,110.0,2.0,150.0,14.91,Adult,0
1,73568.0,2.0,2.0,20.3,89.0,2.0,80.0,3.85,Adult,0
2,73576.0,1.0,2.0,23.2,89.0,2.0,68.0,6.14,Adult,0
3,73577.0,1.0,2.0,28.9,104.0,2.0,84.0,16.15,Adult,0
4,73580.0,2.0,1.0,35.9,103.0,2.0,81.0,10.92,Adult,0
...,...,...,...,...,...,...,...,...,...,...
1961,83711.0,2.0,2.0,33.5,100.0,2.0,73.0,6.53,Adult,0
1962,83712.0,1.0,2.0,30.0,93.0,2.0,208.0,13.02,Adult,0
1963,83713.0,1.0,2.0,23.7,103.0,2.0,124.0,21.41,Adult,0
1964,83718.0,2.0,2.0,27.4,90.0,2.0,108.0,4.99,Adult,0
1965,83727.0,1.0,2.0,24.5,97.0,2.0,108.0,3.76,Adult,0

In [ ]:
from sklearn.model_selection import train_test_split
#from sklearn.model_selection import KFold
#kf = KFold(n_splits = 10)

X= df.drop(['target','age_group','SEQN'],axis='columns')
y= df.target

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

#model = RandomForestClassifier(n_estimators=200)
model = SVC(class_weight='balanced',kernel='linear')
model.get_params()

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': 'balanced',
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'linear',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [ ]:
#cross_val_score(RandomForestClassifier(n_estimators=200),X,y,cv=5)

In [ ]:
#cross_val_score(LogisticRegression(),X,y,cv=5)

In [ ]:
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.7563451776649747

In [ ]:
test_data.fillna(test_data.interpolate(), inplace=True)
X_test_data = test_data[['RIAGENDR','PAQ605','BMXBMI','LBXGLU','DIQ010','LBXGLT','LBXIN']]
y_predicted = model.predict(X_test_data)

In [ ]:
y_predicted

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1])

In [ ]:
result = pd.DataFrame({
    'age_group' : y_predicted
})

In [ ]:
result

     age_group
0            0
1            1
2            1
3            0
4            0
..         ...
307          0
308          0
309          1
310          0
311          1

[312 rows x 1 columns]

In [ ]:
result.to_csv("submission.csv",index=False)